[project]
name = "scientific-contradiction-detection"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "accelerate>=1.13.0",
    "datasets>=4.8.5",
    "faiss-cpu>=1.13.2",
    "nltk>=3.9.4",
    "rank-bm25>=0.2.2",
    "sentence-transformers>=5.5.1",
    "torch==2.9.1",
]

[[tool.uv.index]]
name = "pytorch-cu126"
url = "https://download.pytorch.org/whl/cu126"
explicit = true

[tool.uv.sources]
torch = { index = "pytorch-cu126" }
